services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - dev.env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - $PWD/dist:/srv
    depends_on:
      - frontend
      - backend
  frontend:
    build:
      context: $PWD/frontend
      dockerfile: ./Dockerfile
    volumes:
      - $PWD/dist:/dist
    command: npm run build
    platform: linux/amd64
  backend:
    build:
      context: $PWD/backend
      dockerfile: ./Dockerfile
    volumes:
      - $PWD/backend:/code
    env_file:
      - dev.env

volumes:
  caddy_data:
  caddy_config:



